[package]
name = "bottle_util"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true }
diesel = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
