-- Your SQL goes here
CREATE TABLE album(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    folder_id INTEGER REFERENCES folder(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    added_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE album_work(
    album_id INTEGER NOT NULL REFERENCES album(id) ON DELETE CASCADE,
    work_id INTEGER NOT NULL REFERENCES work(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    PRIMARY KEY (album_id, work_id) ON CONFLICT IGNORE
);

CREATE TABLE folder(
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    parent_id INTEGER REFERENCES folder(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    added_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);