[package]
name = "bottle_download"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { workspace = true }
jpeg-encoder = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
